#!/usr/bin/env bash

set -e

[ -z $1 ] && git commit --amend --no-edit && exit 0

while getopts "i" OPT; do
    case "$OPT" in
        i)
            interactive="true"
            shift
            ;;
    esac
done

if [ -z "$interactive" ]; then
    commit=$(git rev-parse ${1:-HEAD})
else
    commit=$(git fzf-commit)
fi

git commit --fixup $commit
# non-interactive rebase
GIT_SEQUENCE_EDITOR=true git rebase -i --autostash --autosquash $commit^
