#!/usr/bin/env bash

set -e

commit=$( \
    git log --color --pretty=format:"%C(yellow)%h %Creset%s%Cblue [%cn]%Cred%d" --decorate | \
    fzf --ansi --multi \
        --preview 'git show --color {+1}' \
        --preview-window 'right:50%:hidden' \
)

echo -n "$commit" | awk '{printf $1}'

