#!/usr/bin/env bash

set -e

subcommand=${1:-status}

if [[ "$subcommand" =~ ^(co|cmm|cm)$ ]]; then
    subcommand=commit
elif [[ "$subcommand" =~ ^(br)$ ]]; then
    subcommand=branch
elif [[ "$subcommand" =~ ^(st|stat)$ ]]; then
    subcommand=status
fi

git fzf-$subcommand
