#!/usr/bin/env bash

set -e

[ -z "$1" ] && git commit --amend --no-edit && exit 0

usage() { echo "Usage: git amend [-i]" 1>&2; exit 1; }

while getopts "i" OPT; do
    case "$OPT" in
        i)
            interactive="true"
            shift
            ;;
        *)
            usage
            ;;
    esac
done

if [ -n "$interactive" ]; then
    commit=$(git fzf-commit)
else
    commit=$(git rev-parse "${1:-HEAD}")
fi

git commit --fixup "$commit"
# non-interactive rebase
GIT_SEQUENCE_EDITOR=true git rebase -i --autostash --autosquash "$commit"^
