#!/usr/bin/env bash

set -eo pipefail

cd "$(npm prefix)" # go to folder containing the closest package.json

if [ -f pnpm-lock.yaml ]; then
    pnpm "$@"
else
    if [ -f yarn.lock ]; then
        yarn "$@"
    else
        npm "$@"
    fi
fi


